export default {
  date: 'Date',
  time: 'Time',
  greeting: 'Hello',
  languageName: 'English',
  today: 'Today',
  tomorrow: 'Tomorrow',
  currentlyShowingIn: 'Currently showing in',
  fahrenheit: 'Fahrenheit',
  celsius: 'Celsius',
  currentLanguage: 'Current language',
  feelLike: 'Feel like',
  selectYourCity: 'Select Your City',
  language: 'Language',
  searchCity: 'Search city...',
};
